#!/bin/bash

# 1. Ask user for target size in MB (Default: 9)
TARGET_MB=$(zenity --entry --title="Compress Video" --text="Enter Target File Size (MB):" --entry-text="9")

# Exit if user cancels or input is empty
if [ -z "$TARGET_MB" ]; then exit; fi

(
for f in "$@"; do
    echo "# Analyzing $f..."
    
    # 2. Get duration in seconds using ffprobe
    DURATION=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$f")
    
    # Check if duration was found
    if [ -z "$DURATION" ]; then
        zenity --error --text="Could not determine duration for $f"
        continue
    fi

    # 3. Calculate Bitrate
    # Formula: (TargetMB * 8192 kilobits_per_MB) / Duration_seconds = Bitrate_kbps
    # We subtract 128k for audio to be safe, leaving the rest for video.
    
    TOTAL_BITRATE=$(echo "($TARGET_MB * 8192) / $DURATION" | bc)
    VIDEO_BITRATE=$(echo "$TOTAL_BITRATE - 128" | bc)

    # Safety check: prevent negative or too-low bitrates
    if (( $(echo "$VIDEO_BITRATE < 100" | bc -l) )); then
        VIDEO_BITRATE=100
    fi

    echo "# Calculated Bitrate: ${VIDEO_BITRATE}k for ${TARGET_MB}MB target."

    # 4. Run FFmpeg (2-Pass Encoding for Accuracy)
    # Pass 1 (Analysis)
    ffmpeg -y -i "$f" -c:v libx264 -b:v "${VIDEO_BITRATE}k" -pass 1 -an -f null /dev/null
    
    # Pass 2 (Output)
    ffmpeg -y -i "$f" -c:v libx264 -b:v "${VIDEO_BITRATE}k" -pass 2 -c:a aac -b:a 128k "${f%.*}_${TARGET_MB}MB.mp4"

    # Cleanup log files generated by 2-pass
    rm -f ffmpeg2pass-0.log ffmpeg2pass-0.log.mbtree
done
) | zenity --progress --title="Compressing to ${TARGET_MB} MB..." --pulsate --auto-close

zenity --notification --text="Compression Finished!"

